spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=86400000
brevo.api.key=${BREVO_API_KEY}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
